### ISSUE TITLE
pricingStream client

### ISSUE THREAD

**Issue by tarmo1979** [mab05k/oanda-client#6]
I don't know if it's a issue, but how it's possible to read the pricingStream data?

It just keeps waiting for result, but because it's a stream, it would not never come.

Hot it's possible to read continues data of stream?

**Comment by mab05k** [comment]
The two stream endpoints I have not fully tested (haven't used in my production code that is using this library). I think you would need to set up some kind of listener process in your code to listen for updates from oanda's service at those endpoints.

**Comment by mab05k** [comment]
@tarmo1979 Long delay on this, but I've finally got a setup running using the streaming endpoints. An example can be found here https://github.com/mab05k/oanda-client/blob/master/src/Bridge/Symfony/Bundle/Resources/doc/usage/stream_endpoints.md
